"""Unified chart specifications, profiles, and renderer API."""

from __future__ import annotations

from .api import render_chart
from .formatters import (
    DECIMAL_ONE_LABEL,
    TIME_LABEL_MIN2H,
    TIME_LABEL_STANDARD,
    DecimalOneLabel,
    TimeLabelMin2HourDigits,
    TimeLabelStandard,
)
from .layout import compress_activity_time_order, compress_days_time_order
from .profiles import (
    DEFAULT_GROUPED_GRID_PROFILE,
    DEFAULT_PROGRESS_ROWS_PROFILE,
    DEFAULT_WATERFALL_PROFILE,
    MONTHLY_WEEK_METRIC,
    MONTHLY_WEEK_MOOD,
    MONTHLY_WEEK_STUDY,
    QUARTERLY_3MONTH_METRIC,
    QUARTERLY_3MONTH_MOOD,
    QUARTERLY_3MONTH_STUDY,
    TEST_CHART,
    WEEKLY_7DAY_CHART,
    WEEKLY_7DAY_MOOD,
    YEARLY_4QTR_METRIC,
    YEARLY_4QTR_MOOD,
    YEARLY_4QTR_STUDY,
)
from .specs import (
    AnchorRef,
    ChartSpec,
    ColumnTrack,
    GlyphSet,
    GroupedGridProfile,
    HAnchor,
    MonthlyStudyGridSpec,
    MonthlyTrainingGridSpec,
    ProgressRowsProfile,
    QuarterlyStudyCoverageRowsSpec,
    SegmentTrack,
    TrainingBlockRowsSpec,
    TrainingSection,
    TrainingSectionsRowsSpec,
    VerticalBarProfile,
    VerticalBarSpec,
    WaterfallProfile,
    WaterfallSpec,
    WeeklyStudyGridSpec,
    WeeklyTrainingGridSpec,
    YearlyStudyCoverageRowsSpec,
)

__all__ = [
    "render_chart",
    "ChartSpec",
    "HAnchor",
    "AnchorRef",
    "GlyphSet",
    "ColumnTrack",
    "SegmentTrack",
    "VerticalBarProfile",
    "GroupedGridProfile",
    "ProgressRowsProfile",
    "WaterfallProfile",
    "VerticalBarSpec",
    "WeeklyStudyGridSpec",
    "MonthlyStudyGridSpec",
    "MonthlyTrainingGridSpec",
    "WeeklyTrainingGridSpec",
    "TrainingBlockRowsSpec",
    "TrainingSectionsRowsSpec",
    "QuarterlyStudyCoverageRowsSpec",
    "YearlyStudyCoverageRowsSpec",
    "WaterfallSpec",
    "TrainingSection",
    "WEEKLY_7DAY_CHART",
    "WEEKLY_7DAY_MOOD",
    "MONTHLY_WEEK_STUDY",
    "MONTHLY_WEEK_METRIC",
    "MONTHLY_WEEK_MOOD",
    "QUARTERLY_3MONTH_STUDY",
    "QUARTERLY_3MONTH_METRIC",
    "QUARTERLY_3MONTH_MOOD",
    "YEARLY_4QTR_STUDY",
    "YEARLY_4QTR_METRIC",
    "YEARLY_4QTR_MOOD",
    "TEST_CHART",
    "DEFAULT_GROUPED_GRID_PROFILE",
    "DEFAULT_PROGRESS_ROWS_PROFILE",
    "DEFAULT_WATERFALL_PROFILE",
    "TimeLabelStandard",
    "TimeLabelMin2HourDigits",
    "DecimalOneLabel",
    "TIME_LABEL_STANDARD",
    "TIME_LABEL_MIN2H",
    "DECIMAL_ONE_LABEL",
    "compress_days_time_order",
    "compress_activity_time_order",
]
