"""Owned live lesson notes with stable presentation titles."""

from __future__ import annotations

import json
import hashlib
from pathlib import Path
import re
from typing import Any
from uuid import UUID

from learning import storage
from learning.markdown import obsidian_math

_META = "<!-- learning-lesson:"
_START = "<!-- learning-generated:start -->\n"
_END = "<!-- learning-generated:end -->"
_NOTES = (
    "\n\n## Your notes\n\n<!-- Learner annotations are preserved on every update. -->\n"
)


class LessonConflict(ValueError):
    """Publication would replace teaching that the learner may have edited."""


def _digest(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _regions(existing: str, data: dict[str, Any]) -> tuple[str, str, str]:
    """Return learner-owned prefix/suffix and the exact generated bytes."""
    body = existing.split("\n", 2)[2]
    if body.count(_START) != 1 or body.count(_END) != 1:
        raise LessonConflict(
            "lesson has no intact generated region; the existing note is unchanged. "
            "Keep it as a personal note and start a new session, or restore its region markers"
        )
    before, _, tail = body.partition(_START)
    if _END in before:
        raise LessonConflict(
            "lesson region markers are reversed; the existing note is unchanged"
        )
    generated, _, after = tail.partition(_END)
    if "generated_sha256" not in data:
        raise LessonConflict(
            "lesson has no publication fingerprint; the existing note is unchanged. "
            "Keep it as a personal note and start a new session"
        )
    return before, generated, after


def _title(value: str) -> str:
    if not value.strip() or "\n" in value or "\r" in value:
        raise ValueError("lesson title must be nonempty and on one line")
    return value.strip()


def _metadata(text: str) -> dict[str, Any]:
    for line in text.splitlines()[1:2]:
        if line.startswith(_META) and line.endswith(" -->"):
            data = json.loads(line[len(_META) : -4])
            if (
                not isinstance(data, dict)
                or not isinstance(data.get("title"), str)
                or (
                    "scope" in data
                    and (
                        not isinstance(data["scope"], str)
                        or not re.fullmatch(r"[a-z0-9][a-z0-9_-]{0,63}", data["scope"])
                    )
                )
            ):
                raise ValueError("invalid lesson metadata")
            data["title"] = _title(data["title"])
            return data
    return {}


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


def _write(path: Path, text: str, expected: str) -> None:
    current = _read(path)
    if current != expected:
        raise LessonConflict(
            "lesson changed during publication; the current note is unchanged, retry from its latest content"
        )
    if current != text:
        storage.publish_text(path, text)


def _change(
    root: Path, session_id: str, text: str | None, title: str | None, scope: str | None
) -> Path:
    if str(UUID(session_id)) != session_id:
        raise ValueError("session ID must be a canonical lowercase UUID")
    if scope is not None:
        if not re.fullmatch(r"[a-z0-9][a-z0-9_-]{0,63}", scope):
            raise ValueError("invalid lesson scope")
        if not (root / "state" / f"{scope}.json").is_file():
            raise ValueError(f"unknown lesson scope: {scope}")
    if title is not None:
        title = _title(title)
    path = root / "lessons" / f"{session_id}.md"
    marker = f"<!-- learning-session:{session_id} -->"
    # Serialise label changes and Pi publication of the same owned note.
    with storage.lock(root / ".lessons.lock"):
        existing = _read(path)
        if path.exists() and existing.partition("\n")[0] != marker:
            raise ValueError(f"refusing to overwrite an unowned lesson: {path}")
        if text is not None and not text.strip() and not existing:
            return path.resolve()
        if text is None and not existing:
            raise ValueError(f"lesson does not exist: {path}")
        old = _metadata(existing)
        data = dict(old)
        if title is not None:
            data.update(title=title, named=True)
        if scope is not None:
            data["scope"] = scope
        before, previous, after = ("\n", "", _NOTES)
        incoming = obsidian_math(text).rstrip() + "\n" if text is not None else None
        if existing and "generated_sha256" not in old:
            if not old or _START.strip() in existing or _END in existing:
                raise LessonConflict(
                    "lesson metadata or region markers were edited; the existing note is unchanged"
                )
            legacy = existing.split("\n", 2)[2].lstrip("\n")
            if incoming != legacy.rstrip() + "\n":
                after += "\n### Earlier lesson preserved\n\n" + legacy
            data["generated_sha256"] = _digest(previous)
        elif existing:
            before, previous, after = _regions(existing, old)
            if incoming is not None and _digest(previous) != old["generated_sha256"]:
                raise LessonConflict(
                    "the lesson teaching was edited outside the annotation area; "
                    "the existing note is unchanged. Move your edits below the generated "
                    "region and restore the teaching before updating, or start a new session"
                )
        body = incoming if incoming is not None else previous
        if _START.strip() in body or _END in body:
            raise ValueError("teaching cannot contain reserved lesson region markers")
        heading = re.match(r"^#{1,6} +([^\n]+?)(?: +#+)?(?:\n|$)", body)
        if "title" not in data or (not data.get("named") and body.strip()):
            data["title"] = _title(heading[1]) if heading else "Study session"
        if text is not None:
            data["generated_sha256"] = _digest(body)
        encoded = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
        encoded = encoded.replace("<", "\\u003c").replace(">", "\\u003e")
        content = f"{marker}\n{_META}{encoded} -->\n{before}{_START}{body}{_END}{after}"
        _write(path, content, existing)
    return path.resolve()


def publish(root: Path, session_id: str, text: str) -> Path:
    """Publish teaching; an empty branch clears only an existing owned lesson."""
    return _change(root, session_id, text, None, None)


def label(root: Path, session_id: str, *, title: str, scope: str | None = None) -> Path:
    """Name an existing lesson and optionally associate its established course."""
    return _change(root, session_id, None, title, scope)
